# Generated by Django 3.2.9 on 2022-06-18 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novosty', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novosty',
            name='subcategory',
        ),
        migrations.AlterField(
            model_name='novosty',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Novosty', to='novosty.category'),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
